---
apiVersion: v1
kind: ConfigMap
metadata:
  name: djt-mc-bedrock
  labels:
    role: service-config
    app: djt-mc-bedrock
data:
  # Find more options at https://github.com/itzg/docker-minecraft-bedrock-server#server-properties
  # Remove # from in front of line if changing from default values.
  EULA: "TRUE" # Must accept EULA to use this minecraft server
  GAMEMODE: "creative" # Options: survival, creative, adventure
  DIFFICULTY: "easy" # Options: peaceful, easy, normal, hard
  #DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
  LEVEL_NAME: "djt_mc_bedrock"
  LEVEL_SEED: "33480944"
  SERVER_NAME: "djt_mc_bedrock"
  SERVER_PORT: "19132"
  #LEVEL_TYPE: "DEFAULT" # Options: FLAT, LEGACY, DEFAULT
  ALLOW_CHEATS: "true" # Options: true, false
  #MAX_PLAYERS: "10"
  #PLAYER_IDLE_TIMEOUT: "30"
  #TEXTUREPACK_REQUIRED: "false" # Options: true, false
  #
  ## Changing these will have a security impact
  #ONLINE_MODE: "true" # Options: true, false (removes Xbox Live account requirements)
  #WHITE_LIST: "false" # If enabled, need to provide a whitelist.json by your own means. 
  #
  ## Changing these will have a performance impact
  #VIEW_DISTANCE: "10"
  #TICK_DISTANCE: "4"
  #MAX_THREADS: "8"
#---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: djt-mc-bedrock
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: djt-mc-bedrock
  name: djt-mc-bedrock
spec:
  # never more than 1 since djt-mc-bedrock is not horizontally scalable
  replicas: 1
  serviceName: djt-mc-bedrock
  selector:
    matchLabels:
      app: djt-mc-bedrock
  template:
    metadata:
      labels:
        app: djt-mc-bedrock
    spec:
      containers:
        - name: main
          image: 10.69.3.50:5000/djt-mc-bedrock
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: djt-mc-bedrock
          volumeMounts:
            - mountPath: /data
              name: data
          ports:
            - containerPort: 19132
              protocol: UDP
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
            initialDelaySeconds: 300
          livenessProbe: *probe
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: djt-mc-bedrock-service
spec:
  selector:
    app: djt-mc-bedrock
  ports:
    - port: 19132
      targetPort: 19132
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
